name: Deploy FastAPI backend to Azure

on:
  push:
    branches:
      - main

permissions:
  id-token: write  # Needed for OIDC login
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Zip Backend
        run: |
          cd Backend
          zip -r ../Backend.zip .

      - name: Login to Azure using OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'adople-backend'         # :white_check_mark: Name of your Azure Web App
          slot-name: 'Production'            # Or 'staging' if using deployment slots
          package: 'Backend.zip'