name: Deploy FastAPI backend to Azure

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          cd Backend
          pip install -r requirements.txt
          zip -r ../Backend.zip .

      - name: Login to Azure
        uses: azure/login@v1
        with:
          publish-profile: ${{ secrets.AZURE_BACKEND_PUBLISH_PROFILE }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: adople-backend
          slot-name: production
          package: Backend.zip